default:
  tags:
    - shared
    - multitender

stages:
  - test



test-job:
  image: python:3.11
  stage: test
  script:
    - make
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch