image: python:3.11-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  tags:
    - docker

stages:
  - lint
  - test
  - packaging
  - release
  - deploy:dev
  - deploy:prod

.non-release: &non-release
  before_script:
    - apt update && apt install build-essential curl -y
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - when: never

cache:
  paths:
    - .cache/pip
    - .venv/


"Lint application":
  <<: *non-release
  stage: lint
  script:
    - make blacken
    - make lint
    - make format
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"  # Run for all changes to a merge request's source branch

"Type checking":
  <<: *non-release
  stage: lint
  script:
    - make mypy
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'" # Run for all changes to a merge request's source branch


"Test coverage":
  <<: *non-release
  stage: test
  variables:
    TEST_DATABASE_URL: mongodb://localhost:27017/test
  script:
    - make test
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t $CODECOV_TOKEN
  services:
    - mongo:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  # Run for all changes to a merge request's source branch


"Build Container":
  stage: packaging
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $MONGO_PEM
    - mkdir app/lib
    - mv $MONGO_PEM app/lib
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never


"Package Release":
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - >
      release-cli create --name $CI_COMMIT_BRANCH --description $CI_COMMIT_TAG
      --tag-name $CI_COMMIT_BRANCH --ref $CI_COMMIT_SHA
      --assets-link "{\"name\":\"Docker Container\",\"url\":\"https://${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}\"}"
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

.deploy-job:
  tags:
    - shell
  variables:
    DOCKERIMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
    NAME: $UVICORN_ENV.multitender.ru.d
  script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker pull $DOCKERIMAGE
    - docker kill $NAME 1> /dev/null 2> /dev/null && docker rm $NAME 1> /dev/null 2> /dev/null
    - docker run -d \
      --restart=always \
      --net=mynet \
      --name $NAME \
      $DOCKERIMAGE
    - docker logout registry.gitlab.com
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
    - if: '$FORCE_DEPLOY == "true"'
      when: manual

"Deploy To Dev":
  extends: .deploy-job
  stage: deploy:dev
  variables:
    UVICORN_ENV: dev
  environment:
    name: dev
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

"Deploy To Prod":
  extends: .deploy-job
  variables:
    UVICORN_ENV: prod
  stage: deploy:prod
  environment:
    name: prod
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

