version: "3.8"

services:
  app:
    container_name: prod.mt-gateway.multitender.ru.d
    build: .
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - UVICORN_ENV=prod
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    networks:
      - mynet